export const LANGUAGES = [
  "English",
  "Mandarin Chinese",
  "Hindi",
  "Spanish",
  "French",
  "Standard Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "Nigerian Pidgin",
  "Marathi",
  "Telugu",
  "Turkish",
  "Tamil",
  "Yue Chinese (Cantonese)",
  "Vietnamese",
  "Tagalog",
  "Wu Chinese",
  "Korean",
  "Persian (Farsi)",
  "Hausa",
  "Arabic (Egyptian)",
  "Swahili",
  "Javanese",
  "Italian",
  "Punjabi",
  "Kannada",
  "Gujarati",
  "Thai",
].sort();
